### PR TITLE
Initial commit of dev build tools.

### PR DESCRIPTION
**Pull request by kopepasah**
Enclosed are the build tools required for development of the application, including initial Github Actions support.

### CODE REVIEW

**Comment by kopepasah** [comment]
@n8finch this is ready for review.

**Comment by n8finch** [comment]
@kopepasah tested on local, `dev` and `build` scripts work as expected. 

Approving.

The only suggestion I have is to add quick documentation to the README file to install, setup, and run the dev watch and build scripts

**Review by n8finch — APPROVED** [review]

**Review by n8finch — APPROVED** [review]

**Comment by kopepasah** [comment]
@n8finch added some initial documentation. Will need another approval before merging.

**Review by n8finch — APPROVED** [review]

**Comment by n8finch** [comment]
@kopepasah nice, back to you.

**Pull request merged**
